---
trigger: 
- master
pool: Default

stages:
  - stage: Complile
    jobs:
    - job: Compile
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'compile'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      
    


  - stage: Test
    jobs:
    - job: Test
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          
  - stage: Build
    jobs: 
    - job: Build
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: Publish
    jobs:
    - job: Publish
      pool: Default
      steps:
      - task: CopyFiles@2
        inputs:
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
          ArtifactName: 'Maven_demo'
          publishLocation: 'Container'
        


  