---
trigger: 
- master
pool: Default
parameters:
  - name: p1
    type: string
    default: true
    values:
      - true
      - false
    

stages:
          
  - stage: Compile
    jobs: 
    - job: Compile
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'compile'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
  - stage: Test
    dependsOn: Compile
    condition: ${{eq (parameters.P1, true)}}
    jobs: 
    - job: Test
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: SourcecodeVurnerablitiesCheck
    jobs:
    - job: VurnerablitiesCheck
      steps:
      - task: AdvancedSecurity-Dependency-Scanning@1
        
  - stage: SourceCodeVurnerablitiesReport
    jobs:
    - job: Vurnerablitiesreport
      steps:       
      - task: AdvancedSecurity-Publish@1
        
  - stage: CodeQualityCheck
    jobs:
    - job: CodequalityCheck
      steps:
       - task: AdvancedSecurity-Codeql-Init@1
         inputs:
           languages: 'java'
           querysuite: 'security-and-quality'

  - stage: CodeQualityReport
    jobs:
    - job: Codequalityreport
      steps:
       - task: AdvancedSecurity-Codeql-Analyze@1

  - stage: Build
    jobs: 
    - job: Build
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: MavenAuthenticate@0
          inputs:
            artifactsFeeds: 'Nike'
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'deploy'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  