---
trigger: 
- master
pool: Default

stages:
  - stage: Compile
    jobs:
    - job: buildingmavenapp
      displayName: build
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'compile'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
  - stage: ScanningandBuild
    jobs:
    - job: scan
      steps:
      - task: SonarQubePrepare@6
        inputs:
          SonarQube: 'Sonarqube'
          scannerMode: 'MSBuild'
          projectKey: 'sqa_513a33184e8e4c24b5be6318ac283ff44434e005'
          projectName: 'Maven'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.qualitygate.wait=true
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'
      - task: SonarQubeAnalyze@6
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'
      - task: SonarQubePublish@6
        inputs:
          pollingTimeoutSec: '300'

